### PR TITLE
Update DistroSpecial.h

### PR DESCRIPTION
**Pull request by Saijin-Naib**
Upgrade to Alpine v3.14.0

### CODE REVIEW

**Comment by EccentricVamp** [comment]
@agowa338, any movement on this? Seems like a pretty straight forward merge to me.

**Comment by Saijin-Naib** [comment]
At this point I'm more than a few point-releases behind. Maybe I should re-commit with the latest :)

**Comment by EccentricVamp** [comment]
Good point. Security patches are pretty important.

Not sure how to proceed if @agowa338 doesn't respond though. I don't know how the WSL team handles stagnant distros, and whether they'd be willing to let someone else publish to the Windows Store.

**Comment by Saijin-Naib** [comment]
> Good point. Security patches are pretty important.
> 
> Not sure how to proceed if @agowa338 doesn't respond though. I don't know how the WSL team handles stagnant distro launchers, and whether they'd be willing to let someone else publish to the Windows Store.

No idea. I doubt I'm the person for this since my competency is pretty much tapped out with adjusting those lines, haha. I doubt I'd ever be able to triage meaningful issues nor feautre requests :(

**Comment by agowa338** [comment]
> Good point. Security patches are pretty important.

@EccentricVamp Just a reminder for you. You'll have to run a system update via `apk` anyway. Updating the WSL package only affects *new* installations. It doesn't change the data within the filesystem after it has been installed and launched once.

I don't see any security issue, as long as updating via `apk` works.

**Comment by EccentricVamp** [comment]
@agowa338  understood. I actually bumped this issue because I was setting up WSL on a new system and noticed the outdated version. Thanks for the advice though!

**Pull request merged**
